import Link from 'next/link';
import { ArrowRight, BarChart3, BookOpen, BriefcaseBusiness, CheckCircle2, ClipboardList, GitCompareArrows, Network, Sparkles, Target } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { OccupationCard, StatCard } from '@/components/taxonomy-ui';
import { GlobalSearch } from '@/components/client-redirect-search';
import { getPopularOccupations, getStats } from '@/lib/services';

export default function Home() {
  const stats = getStats();
  const popular = getPopularOccupations();
  const explore = [
    { title: 'Occupations', description: 'Browse roles across the OFO taxonomy and explore their associated skills.', href: '/occupations', icon: BriefcaseBusiness, count: '3,039 occupations', color: 'bg-blue-50 text-blue-600' },
    { title: 'Skills', description: 'Understand the capabilities that shape roles, tasks and career pathways.', href: '/skills', icon: Sparkles, count: '13,939 skills', color: 'bg-teal-50 text-teal-600' },
    { title: 'Tasks', description: 'See the practical activities and responsibilities behind each occupation.', href: '/occupations', icon: ClipboardList, count: '4,277 tasks', color: 'bg-amber-50 text-amber-600' },
    { title: 'OFO ↔ ESCO', description: 'Compare local occupations with their closest European counterparts.', href: '/crosswalk', icon: GitCompareArrows, count: '1,000+ mappings', color: 'bg-rose-50 text-rose-600' },
  ];
  return <div className="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 lg:px-10 lg:py-12">
    <section className="relative overflow-hidden rounded-xl border border-slate-200 bg-white px-6 py-10 shadow-[0_12px_36px_rgba(15,23,42,0.04)] sm:px-10 sm:py-14 lg:px-16 lg:py-16"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_top_right,_rgba(29,95,209,0.09),_transparent_60%)]" /><div className="relative max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.16em] text-[#1959c2]"><Network className="h-3.5 w-3.5" />Research taxonomy preview</div><h1 className="max-w-2xl text-4xl font-bold leading-[1.08] tracking-[-0.045em] text-slate-950 sm:text-5xl lg:text-[58px]">Explore the Skills <span className="text-[#1d5fd1]">Mapping Taxonomy</span></h1><p className="mt-5 max-w-xl text-base leading-relaxed text-slate-500">Explore how occupations, skills, tasks and specialisations connect across OFO and ESCO.</p><div className="mt-8 max-w-2xl"><GlobalSearch /></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-[11px] text-slate-400"><span className="font-medium">Try searching:</span><Link href="/occupations/ofo/2021-251201" className="text-slate-600 underline decoration-slate-300 underline-offset-2 hover:text-[#1959c2]">Software Developer</Link><Link href="/skills/skill-001" className="text-slate-600 underline decoration-slate-300 underline-offset-2 hover:text-[#1959c2]">Python Programming</Link><Link href="/crosswalk" className="text-slate-600 underline decoration-slate-300 underline-offset-2 hover:text-[#1959c2]">OFO ↔ ESCO</Link></div></div></section>
    <section className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-5 md:gap-4"><StatCard label="Occupations" value={stats.occupations.toLocaleString()} icon={BriefcaseBusiness} accent="blue" /><StatCard label="Skills" value={stats.skills.toLocaleString()} icon={Sparkles} accent="teal" /><StatCard label="Tasks" value={stats.tasks.toLocaleString()} icon={ClipboardList} accent="amber" /><StatCard label="Specialisations" value={`${stats.specialisations.toLocaleString()}+`} icon={Target} accent="rose" /><StatCard label="OFO ↔ ESCO mappings" value={`${stats.mappings.toLocaleString()}+`} icon={GitCompareArrows} accent="slate" /></section>
    <section className="mt-14"><div className="mb-5 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#1959c2]">Start exploring</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-slate-950">Explore the taxonomy</h2></div><Link href="/occupations" className="hidden items-center gap-1 text-xs font-semibold text-[#1959c2] sm:flex">View all data <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{explore.map(({ title, description, href, icon: Icon, count, color }) => <Link key={title} href={href} className="group"><Card className="h-full border-slate-200 bg-white shadow-none transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-lg ${color}`}><Icon className="h-[18px] w-[18px]" /></span><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#1959c2]" /></div><h3 className="mt-5 text-sm font-bold text-slate-900">{title}</h3><p className="mt-2 text-xs leading-relaxed text-slate-500">{description}</p><p className="mt-4 text-[11px] font-semibold text-slate-400">{count}</p></CardContent></Card></Link>)}</div></section>
    <section className="mt-14"><div className="mb-5 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#1959c2]">Frequently explored</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-slate-950">Popular occupations</h2></div><Link href="/occupations" className="flex items-center gap-1 text-xs font-semibold text-[#1959c2]">Browse occupations <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{popular.map((occupation) => <OccupationCard key={occupation.id} occupation={occupation} />)}</div></section>
    <section className="mt-14 grid gap-4 border-t border-slate-200 pt-8 sm:grid-cols-3"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" /><div><p className="text-xs font-bold text-slate-800">Connected data</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Move from a role to the skills and tasks that define it.</p></div></div><div className="flex gap-3"><BarChart3 className="mt-0.5 h-4 w-4 shrink-0 text-blue-600" /><div><p className="text-xs font-bold text-slate-800">Comparable mappings</p><p className="mt-1 text-xs leading-relaxed text-slate-500">See how OFO and ESCO occupations align.</p></div></div><div className="flex gap-3"><BookOpen className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" /><div><p className="text-xs font-bold text-slate-800">Research-ready context</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Explore a clear, structured view of the taxonomy.</p></div></div></section>
  </div>;
}
