import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowRight, BriefcaseBusiness, GitCompareArrows, Sparkles } from 'lucide-react';
import { getOccupation, getRelatedSkills, getSkill } from '@/lib/services';
import { OccupationLink, SkillCard, SkillTypeBadge } from '@/components/taxonomy-ui';
import { Card, CardContent } from '@/components/ui/card';

export default function SkillDetailPage({ params }: { params: { skillId: string } }) {
  const skill = getSkill(params.skillId);
  if (!skill) notFound();
  const relatedSkills = getRelatedSkills(skill.id);
  const occupations = skill.occupationIds.map((id) => getOccupationById(id)).filter((occupation): occupation is NonNullable<ReturnType<typeof getOccupationById>> => occupation !== undefined);
  function getOccupationById(id: string) { return getOccupation(getOccupationCode(id)); }
  function getOccupationCode(id: string) { const codes: Record<string, string> = { 'occ-001': '2021-251201', 'occ-002': '2021-214501', 'occ-003': '2021-215101', 'occ-004': '2021-721301', 'occ-005': '2021-722301', 'occ-006': '2021-214901', 'occ-007': '2021-251101', 'occ-008': '2021-251102', 'occ-009': '2021-215201', 'occ-010': '2021-252101', 'occ-011': '2021-132501', 'occ-012': '2021-311301' }; return codes[id] || ''; }
  return <div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-8 lg:px-10 lg:py-12"><Link href="/skills" className="mb-7 inline-flex items-center gap-2 text-xs font-semibold text-slate-500 transition hover:text-[#1959c2]"><ArrowLeft className="h-3.5 w-3.5" />Back to skills</Link><section className="rounded-xl border border-slate-200 bg-white shadow-[0_12px_36px_rgba(15,23,42,0.04)]"><div className="border-b border-slate-100 px-6 py-8 sm:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-start"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Sparkles className="h-6 w-6" /></span><div><SkillTypeBadge type={skill.type} /><h1 className="mt-3 text-3xl font-bold tracking-[-0.03em] text-slate-950">{skill.name}</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-500">{skill.description}</p></div></div><div className="rounded-lg border border-slate-200 bg-slate-50 px-5 py-4 text-center"><p className="text-2xl font-bold text-slate-900">{skill.occupationCount}</p><p className="mt-1 text-[11px] text-slate-500">occupations use this skill</p></div></div></div><div className="grid gap-10 p-6 sm:p-10 lg:grid-cols-[1.1fr_0.9fr]"><div><div className="mb-4 flex items-center gap-2"><BriefcaseBusiness className="h-4 w-4 text-blue-600" /><h2 className="text-lg font-bold text-slate-900">Occupations using this skill</h2></div><div className="space-y-2">{occupations.map((occupation) => <OccupationLink key={occupation.id} title={occupation.title} code={occupation.ofoCode} />)}</div></div><div><div className="mb-4 flex items-center gap-2"><GitCompareArrows className="h-4 w-4 text-teal-600" /><h2 className="text-lg font-bold text-slate-900">Related skills</h2></div><div className="grid gap-3">{relatedSkills.map((related) => <Link href={`/skills/${related.id}`} key={related.id} className="group flex items-center justify-between rounded-md border border-slate-100 p-3 transition hover:border-blue-200 hover:bg-blue-50/30"><div><p className="text-sm font-semibold text-slate-800 group-hover:text-[#1959c2]">{related.name}</p><div className="mt-1"><SkillTypeBadge type={related.type} /></div></div><ArrowRight className="h-4 w-4 text-slate-300 group-hover:text-[#1959c2]" /></Link>)}</div></div></div></section></div>;
}
